services:
    notification.type.approve_post:
        class: phpbb_notification_type_approve_post
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.approve_topic:
        class: phpbb_notification_type_approve_topic
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.bookmark:
        class: phpbb_notification_type_bookmark
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.disapprove_post:
        class: phpbb_notification_type_disapprove_post
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.disapprove_topic:
        class: phpbb_notification_type_disapprove_topic
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.pm:
        class: phpbb_notification_type_pm
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.post:
        class: phpbb_notification_type_post
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.post_in_queue:
        class: phpbb_notification_type_post_in_queue
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.quote:
        class: phpbb_notification_type_quote
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.report_pm:
        class: phpbb_notification_type_report_pm
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.report_pm_closed:
        class: phpbb_notification_type_report_pm_closed
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.report_post:
        class: phpbb_notification_type_report_post
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.report_post_closed:
        class: phpbb_notification_type_report_post
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.topic:
        class: phpbb_notification_type_topic
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.type.topic_in_queue:
        class: phpbb_notification_type_topic_in_queue
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    notification.method.email:
        class: phpbb_notification_method_email
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: notification.method }

    notification.method.jabber:
        class: phpbb_notification_method_jabber
        arguments:
            - @notification_manager
            - @dbal.conn
            - @cache.driver
            - @template
            - @ext.manager
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: notification.method }